### ISSUE TITLE
Some images are rendering fuzzily

### ISSUE THREAD

**Issue by reneeblack** [PeaceGeeks/amani#180] opened 2013-08-13 06:36 UTC
![Uploading Screen Shot 2013-08-12 at 11.37.14 PM.png . . .]()

**Comment by MagdiRizkallah** [comment] 2015-08-11 15:48
OELO is having this issue again...

Some of the pictures also appear blurry. The only way I can fix it is by adding a picture to an article at its "original image size" then making the picture smaller to fit the article. If I use the default image size and try to make the picture bigger, it will be blurry. Is that the only way to keep the pictures from appearing unclear? 

An example of a header image that is blurry, even though the source image had good resolution:  http://oelogabon.org/news/mentor-manatee-program-2015.

**Comment by MagdiRizkallah** [comment] 2015-08-12 23:50
duplicate of #767

**Closed by MagdiRizkallah** 2015-08-12 23:50 UTC
Labels: High Priority
